### ISSUE TITLE
Perms

### ISSUE THREAD

**Issue by Sunyccs** [visual-cody/SilkTouchHands#1]
Is there any way to make it so only 1 person has it, not even op?

**Comment by visual-cody** [comment]
This plugin does have permissions. Using a permissions plugin like LuckPerms lets you allow it for a specific user
`/lp user visualcody permission set silktouchhands.silktouch true`

and likewise you can force deny it which you can use on your OP players to prevent them from using it
`/lp user visualcody permission set silktouchhands.silktouch false`
